import {Card, CardAction, CardGameMode} from '../model/CardManager.tsx';

export const getCards = () => {
  let cards: Card[] = [
    {
      id: 1,
      title: 'Ceux qui ont déjà envoyé un nude',
      description: 'Ceux qui ont déjà envoyé un nude boivent 2 gorgées',
      path: 'Card1.jpg',
      seen: false,
      drink: 1,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.WHO, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 2,
      title: 'Le propriétaire bois',
      description: 'Le propriétaire de la carte bois 5 gorgées',
      path: 'Card2.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 3,
      title: "Dis un fantasme si quelqu'un à le même les deux boivent",
      description:
        "Tous le monde dois dire un de ses fantasmes, si quelqu'un a le même que vous, vous buvez tous les deux 3 gorgées",
      path: 'Card3.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 4,
      title: 'Les filles boivent',
      description: 'Les filles boivent 2 gorgées',
      path: 'Card4.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 5,
      title: 'Les garçons boivent',
      description: 'Les garçons boivent 2 gorgées',
      path: 'Card5.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 6,
      title: 'Si tu as un E dans ton prénom bois',
      description: 'Si tu as un E dans ton prénom bois 2 gorgées',
      path: 'Card6.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 7,
      title: 'Change de sens',
      description: 'Change de sens de jeu pas besoin de boire',
      path: 'Card7.jpg',
      seen: false,
      drink: 0,
      action: CardAction.REVERSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 3,
    },
    {
      id: 8,
      title: 'Tous le monde bois',
      description: 'Tous le monde bois 1 gorgée',
      path: 'Card8.jpg',
      seen: false,
      drink: 1,
      action: CardAction.GLOBAL_DRINK,
      mode: [CardGameMode.CLASSIC],
      rarity: 2,
    },
    {
      id: 9,
      title: 'Pioche encore deux carte',
      description: 'Pioche encore deux carte et ne râle pas',
      path: 'Card9.jpg',
      seen: false,
      drink: 0,
      action: CardAction.PICK,
      mode: [CardGameMode.CLASSIC],
      rarity: 2,
    },
    {
      id: 10,
      title: "Bois de l'eau",
      description: "Bois de l'eau c'est important",
      path: 'Card10.jpg',
      seen: false,
      drink: 0,
      action: CardAction.SAFE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO, CardGameMode.HOT],
      rarity: 2,
    },
    {
      id: 11,
      title: 'Pour ou contre Impot du Front ?',
      description:
        "Pour ou contre te faire tatouer 'Impôt' sur le front mais ne pas les payer ? Tous le monde vote, les minoritaires boivent 3 gorgées",
      path: 'Card11.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 12,
      title: 'Plutôt Café ou Chocolat ?',
      description:
        'Plutôt Café ou Chocolat ? Les minoritaires boivent 1 gorgée',
      path: 'Card12.jpg',
      seen: false,
      drink: 1,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 13,
      title: 'The floor is lava',
      description: 'Le dernier a ne plus toucher le sol bois 3 gorgées',
      path: 'Card13.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 14,
      title: 'Embrasse le premier garçon a ta gauche',
      description: 'Embrasse le premier garçon a ta gauche ou bois 5 gorgées',
      path: 'Card14.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 15,
      title: 'Lancé de dé !',
      description: 'Lance le dé et bois le nombre de gorgée indiqué',
      path: 'Card15.jpg',
      seen: false,
      drink: 0,
      action: CardAction.DRINK_DICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 16,
      title: 'Distribue 5',
      description: 'Distribue 5 gorgées comme tu veux mais a un seul joueur',
      path: 'Card16_5.jpg',
      seen: false,
      drink: 5,
      action: CardAction.DISTRIBUTE,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 2,
    },
    {
      id: 17,
      title: 'Bois 4',
      description: 'Bois 4 gorgées',
      path: 'Card16_4.jpg',
      seen: false,
      drink: 4,
      action: CardAction.DRINK,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 2,
    },
    {
      id: 18,
      title: 'Bois 3',
      description: 'Bois 3 gorgées',
      path: 'Card16_3.jpg',
      seen: false,
      drink: 3,
      action: CardAction.DRINK,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 2,
    },
    {
      id: 19,
      title: 'Distribue 2',
      description: 'Distribue 2 gorgées comme tu veux mais a un seul joueur',
      path: 'Card16_2.jpg',
      seen: false,
      drink: 2,
      action: CardAction.DISTRIBUTE,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 2,
    },
    {
      id: 20,
      title: 'Passe ton tour',
      description: 'Passe ton tour et bois 1 gorgée',
      path: 'Card17.jpg',
      seen: false,
      drink: 1,
      action: CardAction.PASS,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 21,
      title: 'Termine ton verre',
      description: 'Termine ton verre et remercie le maître du jeu',
      path: 'Card18.jpg',
      seen: false,
      drink: 10,
      action: CardAction.DRINK,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 2,
    },
    {
      id: 22,
      title: "C'est pas clair wesh ?",
      description:
        'Devine la couleur des sous-vêtements de la personne a ta droite, si tu te trompes bois 2 gorgées',
      path: 'Card19.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 23,
      title: "C'est pas clair wesh ?",
      description:
        'Les autres choisissent une personne a qui tu dois envoyer une disquette sur Instagram',
      path: 'Card20.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 24,
      title: 'Twerk devant tout le monde',
      description: 'Twerk devant tout le monde ou bois 3 gorgées',
      path: 'Card21.jpg',
      seen: false,
      drink: 3,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 25,
      title: 'Tous le monde change de place',
      description: 'Tous le monde change de place mais personne ne bois',
      path: 'Card22.jpg',
      seen: false,
      drink: 0,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 2,
    },
    {
      id: 26,
      title: 'Jeu du dé !',
      description: 'Lance le dé et lis la règle correspondante',
      path: 'Card24.jpg',
      seen: false,
      drink: 0,
      action: CardAction.DRINK_DICE_GAME,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 27,
      title: 'Jeu du regard !',
      description:
        'Tous le monde baisse la tête, au compte de 3 tout le monde lève la tête et regarde une personne, en cas de regard croisé les deux boivent 2 gorgées',
      path: 'Card25.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
    },
    {
      id: 28,
      title: 'Jeu de la valise !',
      description:
        "Chacun son tour, une persone va dire 'Dans ma valise je met ...' et ajoute un objet, la personne suivante doit répéter la phrase et ajouter un objet, si la personne se trompe ou oublie un objet elle bois 2 gorgées",
      path: 'Card26.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 29,
      title: 'Jeu du ni oui ni non !',
      description:
        'Un jeu du ni oui ni non est lancé pour les 4 prochains tours, si tu dis oui ou non tu bois 2 gorgées',
      path: 'Card27.jpg',
      seen: false,
      drink: 0,
      action: CardAction.SAFE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 30,
      title: 'Safe !',
      description: 'Tu es safe pour ce tour',
      path: 'Card28.jpg',
      seen: false,
      drink: 0,
      action: CardAction.SAFE,
      mode: [CardGameMode.CLASSIC],
      rarity: 2,
    },
    {
      id: 31,
      title: 'Message coquin sur Instagram',
      description:
        'Envoie un message coquin a une personne choisi par les autres sur Instagram ou bois 3 gorgées',
      path: 'Card29.jpg',
      seen: false,
      drink: 3,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 32,
      title: '3 raisons de rester célibataire',
      description:
        'Donne 3 raisons de rester célibataire, si les autres sont convaincu tu bois 3',
      path: 'Card30.jpg',
      seen: false,
      drink: 3,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT, CardGameMode.WHO, CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 33,
      title: 'Petite story snap ?',
      description:
        "Publie en story snap (privé ou public c'est le choix des autres) que tu n'es plus vierge / puceau !",
      path: 'Card31.jpg',
      seen: false,
      drink: 5,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 34,
      title: 'Le plus vieux et la plus jeune',
      description:
        'Le plus vieux et la plus jeune vont pendant 5 minutes dans une pièce a part, le plus vieux partage tes connaissances en cul avec le plus jeune :)',
      path: 'Card32.jpg',
      seen: false,
      drink: 2,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT, CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 35,
      title: 'Pêcho ce soir ?',
      description: 'Les joueurs qui veulent pêcho ce soir boivent 4 gorgées',
      path: 'Card33.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 36,
      title: 'Bras de fer avec la personne a ta gauche',
      description:
        'Fait un bras de fer avec la personne a ta gauche, si tu perds bois 2 gorgées',
      path: 'Card34.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 2,
    },
    {
      id: 37,
      title: 'Battle de drague',
      description:
        'Battle de drague le groupe vote pour le meilleur dragueur, le perdant bois 1 gorgées',
      path: 'Card35.jpg',
      seen: false,
      drink: 1,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 38,
      title: 'Tu as 5 secondes pour ...',
      description:
        'Tu as 5 secondes pour dire combien il y a de personnes dans la pièce, si tu te trompes bois 2 gorgées',
      path: 'Card36.jpg',
      seen: false,
      drink: 2,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 39,
      title: 'Vodka ? tu bois',
      description: 'Les joueurs qui jouent avec de la vodka boivent 4 gorgées',
      path: 'Card37.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 40,
      title: "Sorti de l'Europe ? tu bois",
      description:
        "Les joueurs qui ont voté pour la sortie de l'Europe boivent 3 gorgées",
      path: 'Card38.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 41,
      title: 'Ceux qui ont un tatouage boivent',
      description: 'Tous ceux qui ont un tatouage boivent 3 gorgées',
      path: 'Card39.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 42,
      title: 'Les droiteux boivent',
      description:
        'Les droitiers boivent 2 gorgées, les gauchers sont safe pour ce tour',
      path: 'Card40.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 43,
      title: 'Une ex dans la salle ?',
      description:
        'Ceux qui ont une ex dans la salle boivent 4 gorgées, si tu as plusieurs ex tu bois 1 gorgée par ex',
      path: 'Card41.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 44,
      title: 'Ceux qui font du sport distribuent 3',
      description:
        'Tous ceux qui font du sport distribuent 3 gorgées comme ils veulent mais a un seul joueur',
      path: 'Card42.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 45,
      title: 'Sextape ?',
      description: 'Ceux qui ont déjà fait une sextape boivent 5 gorgées',
      path: 'Card43.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 46,
      title: 'Changes tue le PQ vide',
      description:
        "Ceux qui ne changent jamais le PQ vide boivent 3 gorgées, si tu n'as pas de PQ chez toi bois 5 gorgées",
      path: 'Card44.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 47,
      title: 'Yeux verts ?',
      description: 'Ceux qui ont les yeux verts boivent 2 gorgées',
      path: 'Card45.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 48,
      title: 'Yeux marron ?',
      description: 'Ceux qui ont les yeux marron boivent 2 gorgées',
      path: 'Card46.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 49,
      title: 'Yeux bleus ?',
      description: 'Ceux qui ont les yeux bleus boivent 2 gorgées',
      path: 'Card47.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 50,
      title: 'Un O dans ton prénom ?',
      description: 'Si tu as un O dans ton prénom bois 2 gorgées,',
      path: 'Card48.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 51,
      title: 'Un A dans ton prénom ?',
      description: 'Si tu as un A dans ton prénom bois 2 gorgées',
      path: 'Card49.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 52,
      title: 'Tu portes du bleu ?',
      description: 'Ceux qui portent du bleu boivent 3 gorgées',
      path: 'Card50.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 53,
      title: 'Tu portes du blanc ?',
      description: 'Ceux qui portent du blanc boivent 3 gorgées',
      path: 'Card51.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 54,
      title: 'Tu portes du gris ?',
      description: 'Ceux qui portent du gris boivent 3 gorgées',
      path: 'Card52.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 55,
      title: 'Ceux qui ont déjà dormi ensemble',
      description:
        'Ceux qui ont déjà dormi ensemble (autre que partenaire officiel) boivent 5 gorgées',
      path: 'Card53.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 56,
      title: 'Chambre des parents fait ?',
      description:
        'Ceux qui ont déjà fait dans la chambre des parents boivent 5 gorgées',
      path: 'Card54.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 57,
      title: 'Fait un kiss',
      description: 'Tu dois faire un kiss, les autres choisissent avec qui',
      path: 'Card55.jpg',
      seen: false,
      drink: 4,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 58,
      title: 'Poste sur tiktok ?',
      description: 'Ceux qui ont déjà posté sur tiktok boivent 2 gorgées',
      path: 'Card56.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 59,
      title: 'Tu touches ton nez avec ta langue ?',
      description:
        'Ceux qui arrivent a toucher leur nez avec leur langue boivent 3 gorgées',
      path: 'Card57.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 60,
      title: 'Rêve érotique cette semaine ?',
      description:
        'Ceux qui ont eu un rêve érotique cette semaine boivent 5 gorgées',
      path: 'Card58.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 61,
      title: 'Permis ? Tu donnes',
      description: 'Ceux qui ont le permis donnent 3 gorgées',
      path: 'Card59.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 62,
      title: 'En couple ? Tu bois',
      description: 'Ceux qui sont en couple boivent 4 gorgées',
      path: 'Card60.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 63,
      title: 'Ceux qui ont pêcho la soeur/le frère d’un pote',
      description:
        'Ceux qui ont pêcho la soeur/le frère d’un pote boivent 5 gorgées',
      path: 'Card61.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 64,
      title: 'Lunettes ? Tu bois',
      description: 'Ceux qui portent des lunettes boivent 4 gorgées',
      path: 'Card62.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 65,
      title: 'Tu as balancé le mensonge du père noël ?',
      description:
        'Ceux qui ont déjà dit a un enfant que le père noël n’existe pas boivent 5 gorgées',
      path: 'Card63.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 66,
      title: "Je n'ai jamais voulu pêcho quelqu'un ici",
      description:
        "Je n'ai jamais voulu pêcho quelqu'un ici, si tu as déjà voulu pêcho quelqu'un ici bois 4 gorgées",
      path: 'Card64.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 67,
      title: 'Déjà inscrit sur un site de rencontre ?',
      description:
        'Ceux qui sont déjà inscrit sur un site de rencontre boivent 2 gorgées',
      path: 'Card.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 68,
      title: 'Cite 3 personnes que tu veux pousser dans les escaliers',
      description: 'Cite 3 personnes que tu veux pousser dans les escaliers',
      path: 'Card66.jpg',
      seen: false,
      drink: 2,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 69,
      title: 'Ceux qui ont déjà embrassé quelqu’un ?',
      description: 'Ceux qui ont déjà embrassé quelqu’un boivent 1 gorgées',
      path: 'Card67.jpg',
      seen: false,
      drink: 1,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 70,
      title:
        'Tous le monde pointe du doigt la personne qui peut ken ce soir (hors couple)',
      description:
        'Tous le monde pointe du doigt la personne qui peut ken ce soir (hors couple), si tu es pointé bois 3 gorgées',
      path: 'Card68.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 71,
      title: 'Qui a le plus beau cul',
      description:
        'Tous le monde pointe du doigt la personne qui a le plus beau cul, si tu es pointé bois 4 gorgées',
      path: 'Card69.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 72,
      title: 'Cheveux blonds ?',
      description: 'Ceux qui ont les cheveux blonds boivent 3 gorgées',
      path: 'Card70.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 73,
      title: 'Cheveux colorés ?',
      description: 'Ceux qui ont les cheveux colorés boivent 2 gorgées',
      path: 'Card71.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 74,
      title: 'Tu as des animaux ?',
      description: 'Ceux qui ont des animaux boivent 1 gorgées par animal',
      path: 'Card72.jpg',
      seen: false,
      drink: 1,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 75,
      title: 'Ajoute de l’alcool dans le verre a droite',
      description:
        'Ajoute de l’alcool dans le verre a droite, si tu n’as pas de verre a droite bois 3 gorgées',
      path: 'Card73.jpg',
      seen: false,
      drink: 0,
      action: CardAction.SAFE,
      mode: [CardGameMode.CLASSIC],
      rarity: 2,
    },
    {
      id: 76,
      title: 'La personne avec les plus gros seins distribue 2',
      description: 'La personne avec les plus gros seins distribue 2 gorgées',
      path: 'Card74.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 77,
      title: 'Bois avec le voisin de gauche',
      description: 'Bois avec le voisin de gauche',
      path: 'Card75.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 2,
    },
    {
      id: 78,
      title: 'Qui est le plus attirant selon toi ?',
      description: 'Selon toi qui est le plus attirant dans la pièce ?',
      path: 'Card76.jpg',
      seen: false,
      drink: 4,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 79,
      title: 'Kill Marry, Kiss & Fuck',
      description:
        'Choisis une personne a tué, une personne a épousé, une a embrassé et une a baisé',
      path: 'Card77.jpg',
      seen: false,
      drink: 3,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 3,
    },
    {
      id: 80,
      title: 'Donne autant de gorgées que tu as de sextoys',
      description: 'Donne autant de gorgées que tu as de sextoys chez toi !',
      path: 'Card78.jpg',
      seen: false,
      drink: 2,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 81,
      title: 'Mime métier',
      description:
        'Mime un métier (Chanteur, Pêcheur, ...). Si les autres devinent tu donnes 3 sinon tu bois 2 !',
      path: 'Card79.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 82,
      title: 'Mime animal',
      description:
        'Mime un animal (Chat, Chien, ...). Si les autres devinent tu donnes 3 sinon tu bois 2 !',
      path: 'Card80.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 83,
      title: 'Mime animal',
      description:
        "Mime un verbe d'action (manger, dormir, ...). Si les autres devinent tu donnes 3 sinon tu bois 2 !",
      path: 'Card81.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 84,
      title: 'Shi fu mi',
      description: 'Shi fu mi, le perdant bois 3 gorgées',
      path: 'Card82.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 85,
      title: 'Shi fu mi',
      description: 'Shi fu mi, le perdant bois 3 gorgées',
      path: 'Card83.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 86,
      title: 'Calin a droite',
      description: 'Fait un calin a la personne a ta droite ou bois 2',
      path: 'Card84.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 87,
      title: 'Calin a gauche',
      description: 'Fait un calin a la personne a ta gauche ou bois 2',
      path: 'Card85.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 88,
      title: 'Take a shot !',
      description: 'Take a shot !',
      path: 'Card86.jpg',
      seen: false,
      drink: 10,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 3,
    },
    {
      id: 89,
      title: 'Jeu de la bouteille',
      description:
        'Fait tournée une bouteille, tu embrasses la personne pointé ou bois 5',
      path: 'Card87.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT],
      rarity: 2,
    },
    {
      id: 90,
      title: 'Récite chaque prénom',
      description:
        'Récite chaque prénom de la pièce, si tu te trompes bois 4 gorgées',
      path: 'Card88.jpg',
      seen: false,
      drink: 4,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 91,
      title: 'Les féssés !',
      description:
        'Laisse chaque joueur te donner une fessée, ou bois autant de gorgées que de joueurs',
      path: 'Card89.jpg',
      seen: false,
      drink: 5,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 92,
      title: 'La personne la plus petite bois 3',
      description: 'La personne la plus petite bois 3 gorgées',
      path: 'Card90.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 93,
      title: 'Prochain anniversaire',
      description: 'La personne qui a son anniversaire le plus proche bois 3',
      path: 'Card91.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 94,
      title: "Le groupe choisi deux personnes pour s'enfermer dans une pièce",
      description:
        'Le groupe choisi deux personnes pour s’enfermer dans une pièce',
      path: 'Card92.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 95,
      title: 'Echange t-shirt',
      description:
        'Echange ton t-shirt avec une personne choisie par les autres, ou bois 2',
      path: 'Card93.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 96,
      title: 'Bisous a tous le monde la ou ils veulent',
      description:
        'Fait un bisous a tous le monde la ou ils veulent sinon bois autant que de personne',
      path: 'Card94.jpg',
      seen: false,
      drink: 5,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 97,
      title: 'Une chanson ?',
      description: 'Chante une chanson ou bois 3 gorgées',
      path: 'Card95.jpg',
      seen: false,
      drink: 3,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 98,
      title: 'Donne 7 gorgées a la personne que tu connais le mieux',
      description: 'Donne 7 gorgées a la personne que tu connais le mieux',
      path: 'Card96.jpg',
      seen: false,
      drink: 7,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 99,
      title: "Bois autant que tu as d'ex",
      description: 'Bois autant que tu as d’ex',
      path: 'Card97.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 100,
      title: "La personne qui a le moins d'abbonés sur Instagram bois 4",
      description: 'La personne qui a le moins d’abonnés sur Instagram bois 4',
      path: 'Card98.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 101,
      title: 'Créer un couple !',
      description:
        'Créer un couple les deux personnes devront boire ensemble jusqu’à la fin du jeu',
      path: 'Card99.jpg',
      seen: false,
      drink: 0,
      action: CardAction.COUPLE,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 102,
      title: 'Distribue autant que tu as d’ex',
      description: 'Distribue autant de gorgées que tu as d’ex',
      path: 'Card100.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 103,
      title: 'La personne qui lis la carte bois 2',
      description: 'Distribue autant de gorgées que tu as d’ex',
      path: 'Card101.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 104,
      title: 'Première personne arrivée a la soirée distribue 3',
      description:
        'La première personne a être arrivée a la soirée distribue 3 gorgées',
      path: 'Card102.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 105,
      title: 'Les personnes qui prêtent leurs comptes Netflix distribuent 5',
      description:
        'Toutes les personnes qui prêtent leurs comptes Netflix distribuent 5 gorgées',
      path: 'Card103.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 106,
      title: 'Bu en cours ?',
      description: 'Les personnes qui ont déjà bu en cours boivent 2',
      path: 'Card104.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 107,
      title: 'Embrasse les fesses',
      description: "Embrasse les fesses d'une personne ou bois 3",
      path: 'Card105.jpg',
      seen: false,
      drink: 3,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 108,
      title: 'Les filles boivent taille seins',
      description:
        'Les filles boivent autant de gorgées que leur taille de seins (A=1, B=2, ...)',
      path: 'Card109.jpg',
      seen: false,
      drink: 0,
      action: CardAction.SAFE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 109,
      title: "3 choses qu'un petit copain parfait doit avoir",
      description: 'Cite 3 choses qu’un petit copain parfait pourrait faire',
      path: 'Card107.jpg',
      seen: false,
      drink: 2,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 110,
      title: 'As tu déjà comparé les tailles de bites ?',
      description:
        'Ceux qui ont déjà comparé la taille de leurs bites boivent 3 gorgées',
      path: 'Card108.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 111,
      title: 'Créer un couple !',
      description:
        'Créer un couple les deux personnes devront boire ensemble jusqu’à la fin du jeu',
      path: 'Card109.jpg',
      seen: false,
      drink: 0,
      action: CardAction.COUPLE,
      mode: [CardGameMode.CLASSIC, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 112,
      title: '5 au premier arrivé ou 2 à tous',
      description:
        'Tu as le choix entre donner 5 gorgées au premier arrivé ou 2 a tous',
      path: 'Card110.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 113,
      title: 'Tu dors nu ?',
      description: 'Ceux qui dorment nu boivent 1 gorgées',
      path: 'Card111.jpg',
      seen: false,
      drink: 1,
      action: CardAction.CHOICE,
      mode: [CardGameMode.WHO, CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 114,
      title: 'Le premier joueur qui sort un préservatif',
      description:
        'Rapidité ! Le premier joueur qui sort un préservatif donne 4',
      path: 'Card112.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 115,
      title: 'Tu as déjà regarder du porno ?',
      description: 'Ceux qui ont déjà regardé du porno boivent 2',
      path: 'Card113.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 116,
      title: '3 choses que tu aimes sentir',
      description:
        'Cites 3 choses que tu aimes sentir, les autres doivent valider',
      path: 'Card114.jpg',
      seen: false,
      drink: 3,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 117,
      title: 'Bras de fer chinois',
      description: 'Bras de fer chinois lancé ! Le perdant bois 2',
      path: 'Card115.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 118,
      title: 'Bois ton nombre de bijoux actuel',
      description: 'Bois autant de gorgées que tu as de bijoux !',
      path: 'Card116.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 119,
      title: "3 choses qui tombent avec l'âge",
      description: 'Cite 3 choses qui tombent avec l’âge ou bois 2',
      path: 'Card117.jpg',
      seen: false,
      drink: 2,
      action: CardAction.ACTION,
      mode: [CardGameMode.HOT, CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 120,
      title: '3 choses que tu dis quand tu vois un bébé moche',
      description: 'Cite 3 choses que tu dis quand tu vois un bébé moche',
      path: 'Card118.jpg',
      seen: false,
      drink: 3,
      action: CardAction.ACTION,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 121,
      title: 'Tes voisins boivent',
      description: 'Les personnes a ta gauche et a ta droite boivent 2',
      path: 'Card119.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 122,
      title: 'Tu dors en pijama ?',
      description: 'Ceux qui dorment en pijama boivent 2',
      path: 'Card120.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 123,
      title: 'Donner les prix de vos chaussures les plus chères bois',
      description:
        'Donner les prix de vos chaussures, la personne avec la pair la plus chère bois 5',
      path: 'Card121.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 124,
      title: 'Bois avec personne en face',
      description: 'Toi et la personne en face boivent 2',
      path: 'Card122.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 125,
      title: 'Première fille a montrer son soutif',
      description: 'La première fille a montrer son soutif donne 5',
      path: 'Card123.jpg',
      seen: false,
      drink: 5,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.HOT],
      rarity: 1,
    },
    {
      id: 126,
      title: 'Tu as déjà regarder du porno ?',
      description: 'Ceux qui ont déjà regardé du porno boivent 2',
      path: 'Card124.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 127,
      title: 'Le plus vieux bois',
      description: 'La personne la plus âgé ici bois 4',
      path: 'Card125.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 128,
      title: 'Tu as déjà trompé ?',
      description:
        'Ceux qui ont déjà trompé leur partenaire prennent la sanction ultime : 10',
      path: 'Card126.jpg',
      seen: false,
      drink: 10,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 129,
      title: 'Ah tu fumes batard ?',
      description: 'Ceux qui fument boivent 3',
      path: 'Card127.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 130,
      title: 'Tu dors en sous-vêtements ?',
      description: 'Ceux qui dorment en sous-vêtements boivent 3',
      path: 'Card128.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.HOT, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 131,
      title: 'Bois avec qui tu veux',
      description: 'Bois avec qui tu veux 3 gorgées',
      path: 'Card129.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 132,
      title: 'Les personnes qui portent du Calvin Klein boivent 2',
      description: 'Ceux qui portent du Calvin Klein boivent 2 gorgées',
      path: 'Card130.jpg',
      seen: false,
      drink: 2,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC, CardGameMode.WHO],
      rarity: 1,
    },
    {
      id: 133,
      title: 'Dernier arrivé ?',
      description:
        'La dernière personne arrivée boit 4 (fallait venir avant mauvaise fois)',
      path: 'Card131.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 134,
      title: 'Le plus grand ici bois',
      description: 'La personne la plus grande ici bois 3',
      path: 'Card132.jpg',
      seen: false,
      drink: 3,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 135,
      title: 'Plus de fille ou de mec ?',
      description:
        "Si il y a plus de filles les garçons boivent 4 si c'est l'inverse les filles boivent 4",
      path: 'Card133.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOICE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
    {
      id: 136,
      title: 'Dernier a se lever',
      description: 'La dernière personne a se lever bois 4',
      path: 'Card134.jpg',
      seen: false,
      drink: 4,
      action: CardAction.CHOOSE,
      mode: [CardGameMode.CLASSIC],
      rarity: 1,
    },
  ];

  return cards;
};
